# ryan louie Theme/Blog - Jekyll Theme
# the glas theme: https://github.com/SpaceG/glas
# Author: LucasGatsas
# Theme: glas
# Source: https://github.com/spaceg/glas
# Mail: space@youralien.github.io
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Louie
#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # "
  PhD candidate at Northwestern in Technology and Social Behavior. HCI + AI. Currently based in Chicago.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://youralien.github.io" # the base hostname & protocol for your site

#These settings might be able to go?
author: Ryan Louie

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /project/:title.html

# Google Analytics
google_analytics: UA-101675001-2